import { db, setDoc, doc } from './firebase';
import { Participant, Team, Submission, Evaluation, Announcement, OpsReport, EventActivity } from '../types';

export const SEEDED_PARTICIPANTS: Participant[] = [
  {
    id: 'part-1',
    uid: 'part-1',
    name: 'Yash Gawde',
    email: 'yash@veyra.io',
    college: 'TCET Mumbai',
    skills: ['React', 'TypeScript', 'Node.js', 'Firebase'],
    role: 'Frontend Lead',
    projectInterests: ['Healthcare', 'DevTools', 'AI'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    qrCodeId: 'VEYRA-PART-001',
    teamId: 'team-1',
    teamName: 'Team Nova',
  },
  {
    id: 'part-2',
    uid: 'part-2',
    name: 'Aarav Sharma',
    email: 'aarav@veyra.io',
    college: 'IIT Bombay',
    skills: ['Python', 'PyTorch', 'Gemini API', 'FastAPI'],
    role: 'ML Engineer',
    projectInterests: ['Healthcare', 'AI', 'Automation'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    qrCodeId: 'VEYRA-PART-002',
    teamId: 'team-1',
    teamName: 'Team Nova',
  },
  {
    id: 'part-3',
    uid: 'part-3',
    name: 'Priya Patel',
    email: 'priya@veyra.io',
    college: 'VJTI Mumbai',
    skills: ['Figma', 'UI/UX', 'Tailwind', 'Design Systems'],
    role: 'Product Designer',
    projectInterests: ['Healthcare', 'EdTech'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 135).toISOString(),
    qrCodeId: 'VEYRA-PART-003',
    teamId: 'team-1',
    teamName: 'Team Nova',
  },
  {
    id: 'part-4',
    uid: 'part-4',
    name: 'Rohan Mehta',
    email: 'rohan@veyra.io',
    college: 'BITS Pilani',
    skills: ['Go', 'Kubernetes', 'PostgreSQL', 'Docker'],
    role: 'Backend Engineer',
    projectInterests: ['FinTech', 'DevOps'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    qrCodeId: 'VEYRA-PART-004',
    teamId: 'team-2',
    teamName: 'Team Vector',
  },
  {
    id: 'part-5',
    uid: 'part-5',
    name: 'Ananya Roy',
    email: 'ananya@veyra.io',
    college: 'DTU Delhi',
    skills: ['Flutter', 'Dart', 'Firebase'],
    role: 'Mobile Developer',
    projectInterests: ['FinTech', 'Social Impact'],
    checkedIn: false,
    qrCodeId: 'VEYRA-PART-005',
    teamId: 'team-2',
    teamName: 'Team Vector',
  },
  {
    id: 'part-6',
    uid: 'part-6',
    name: 'Vikram Singh',
    email: 'vikram@veyra.io',
    college: 'NIT Trichy',
    skills: ['React Native', 'Node.js', 'GraphQL'],
    role: 'Fullstack Developer',
    projectInterests: ['Smart Cities', 'FinTech'],
    checkedIn: false,
    qrCodeId: 'VEYRA-PART-006',
    teamId: 'team-2',
    teamName: 'Team Vector',
  },
  {
    id: 'part-7',
    uid: 'part-7',
    name: 'Neha Gupta',
    email: 'neha@veyra.io',
    college: 'IIIT Hyderabad',
    skills: ['Computer Vision', 'TensorFlow', 'Python'],
    role: 'AI Researcher',
    projectInterests: ['Computer Vision', 'Robotics'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    qrCodeId: 'VEYRA-PART-007',
    teamId: 'team-3',
    teamName: 'Team Apex',
  },
  {
    id: 'part-8',
    uid: 'part-8',
    name: 'Devansh Shah',
    email: 'devansh@veyra.io',
    college: 'SPIT Mumbai',
    skills: ['Next.js', 'TypeScript', 'TailwindCSS'],
    role: 'Frontend Engineer',
    projectInterests: ['Computer Vision', 'Web3'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    qrCodeId: 'VEYRA-PART-008',
    teamId: 'team-3',
    teamName: 'Team Apex',
  },
  {
    id: 'part-9',
    uid: 'part-9',
    name: 'Ishita Verma',
    email: 'ishita@veyra.io',
    college: 'KJSCE Mumbai',
    skills: ['Rust', 'Solidity', 'Cryptography'],
    role: 'Blockchain Developer',
    projectInterests: ['Web3', 'Cybersecurity'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    qrCodeId: 'VEYRA-PART-009',
    teamId: 'team-4',
    teamName: 'Team Quantum',
  },
  {
    id: 'part-10',
    uid: 'part-10',
    name: 'Siddharth Rao',
    email: 'siddharth@veyra.io',
    college: 'COEP Pune',
    skills: ['C++', 'Embedded Systems', 'IoT'],
    role: 'Hardware Specialist',
    projectInterests: ['Smart Cities', 'IoT'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    qrCodeId: 'VEYRA-PART-010',
    teamId: 'team-4',
    teamName: 'Team Quantum',
  },
  {
    id: 'part-11',
    uid: 'part-11',
    name: 'Kavya Nair',
    email: 'kavya@veyra.io',
    college: 'MIT Manipal',
    skills: ['Python', 'Pandas', 'Data Analysis'],
    role: 'Data Scientist',
    projectInterests: ['Climate Tech', 'AI'],
    checkedIn: true,
    checkedInAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    qrCodeId: 'VEYRA-PART-011',
    teamId: 'team-5',
    teamName: 'Team CyberPulse',
  },
  {
    id: 'part-12',
    uid: 'part-12',
    name: 'Sameer Khan',
    email: 'sameer@veyra.io',
    college: 'PES University',
    skills: ['Node.js', 'Express', 'MongoDB'],
    role: 'Backend Developer',
    projectInterests: ['Climate Tech', 'DevTools'],
    checkedIn: false,
    qrCodeId: 'VEYRA-PART-012',
    teamId: 'team-5',
    teamName: 'Team CyberPulse',
  },
];

export const SEEDED_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Team Nova',
    tagline: 'AI-driven rapid emergency response platform for rural clinics',
    description: 'NovaCare leverages Gemini multimodal vision models to triage patient vital scans.',
    leaderId: 'part-1',
    memberIds: ['part-1', 'part-2', 'part-3'],
    members: [
      { participantId: 'part-1', name: 'Yash Gawde', role: 'Frontend Lead', checkedIn: true },
      { participantId: 'part-2', name: 'Aarav Sharma', role: 'ML Engineer', checkedIn: true },
      { participantId: 'part-3', name: 'Priya Patel', role: 'Product Designer', checkedIn: true },
    ],
    projectInterests: ['Healthcare', 'AI'],
    lookingForSkills: ['DevOps'],
    riskLevel: 'LOW',
    riskFactors: ['All 3/3 members checked in', 'Recent repository activity', 'Submission completed'],
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    submissionId: 'sub-1',
  },
  {
    id: 'team-2',
    name: 'Team Vector',
    tagline: 'Cross-border offline-first micropayments engine',
    description: 'Enabling instant offline settlements using cryptographic state channels.',
    leaderId: 'part-4',
    memberIds: ['part-4', 'part-5', 'part-6'],
    members: [
      { participantId: 'part-4', name: 'Rohan Mehta', role: 'Backend Engineer', checkedIn: true },
      { participantId: 'part-5', name: 'Ananya Roy', role: 'Mobile Developer', checkedIn: false },
      { participantId: 'part-6', name: 'Vikram Singh', role: 'Fullstack Developer', checkedIn: false },
    ],
    projectInterests: ['FinTech'],
    lookingForSkills: ['React Native', 'Cryptography'],
    riskLevel: 'HIGH',
    riskFactors: [
      'No team activity for 110 minutes',
      'Only 1/3 members checked in at venue',
      'No submission draft uploaded',
    ],
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
  },
  {
    id: 'team-3',
    name: 'Team Apex',
    tagline: 'Autonomous drone fleet navigation for urban search & rescue',
    description: 'Real-time thermal spatial mapping powered by edge computer vision models.',
    leaderId: 'part-7',
    memberIds: ['part-7', 'part-8'],
    members: [
      { participantId: 'part-7', name: 'Neha Gupta', role: 'AI Researcher', checkedIn: true },
      { participantId: 'part-8', name: 'Devansh Shah', role: 'Frontend Engineer', checkedIn: true },
    ],
    projectInterests: ['Computer Vision', 'Robotics'],
    lookingForSkills: ['Backend Engineer'],
    riskLevel: 'LOW',
    riskFactors: ['All 2/2 members checked in', 'Active submission draft'],
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    submissionId: 'sub-3',
  },
  {
    id: 'team-4',
    name: 'Team Quantum',
    tagline: 'Decentralized smart grid energy trading protocol',
    description: 'Zero-knowledge proofs for peer-to-peer solar microgrid energy settlement.',
    leaderId: 'part-9',
    memberIds: ['part-9', 'part-10'],
    members: [
      { participantId: 'part-9', name: 'Ishita Verma', role: 'Blockchain Developer', checkedIn: true },
      { participantId: 'part-10', name: 'Siddharth Rao', role: 'Hardware Specialist', checkedIn: true },
    ],
    projectInterests: ['Web3', 'IoT'],
    lookingForSkills: ['UI/UX Designer'],
    riskLevel: 'MEDIUM',
    riskFactors: ['Low commit frequency in last 60 minutes', 'Partial submission outline'],
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    submissionId: 'sub-4',
  },
  {
    id: 'team-5',
    name: 'Team CyberPulse',
    tagline: 'AI threat intelligence & automated vulnerability patching',
    description: 'Scanning containerized microservices for zero-day vulnerabilities in real time.',
    leaderId: 'part-11',
    memberIds: ['part-11', 'part-12'],
    members: [
      { participantId: 'part-11', name: 'Kavya Nair', role: 'Data Scientist', checkedIn: true },
      { participantId: 'part-12', name: 'Sameer Khan', role: 'Backend Developer', checkedIn: false },
    ],
    projectInterests: ['Cybersecurity', 'DevTools'],
    lookingForSkills: ['DevOps'],
    riskLevel: 'MEDIUM',
    riskFactors: ['1/2 members absent from check-in', 'Submission draft in progress'],
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    submissionId: 'sub-5',
  },
];

export const SEEDED_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    teamId: 'team-1',
    teamName: 'Team Nova',
    title: 'NovaCare AI',
    tagline: 'Multimodal Emergency Triage Platform',
    description: 'NovaCare uses Gemini 1.5 Flash to analyze patient symptoms and medical image scans in real time.',
    demoUrl: 'https://novacare-demo.vercel.app',
    repoUrl: 'https://github.com/teamnova/novacare',
    videoUrl: 'https://youtube.com/watch?v=demo-nova',
    techStack: ['React', 'TypeScript', 'Gemini API', 'Firebase'],
    submittedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'sub-3',
    teamId: 'team-3',
    teamName: 'Team Apex',
    title: 'ApexVision Drone Ops',
    tagline: 'Thermal AI Navigation Engine',
    description: 'Autonomous thermal spatial mapper for disaster response drone fleets.',
    demoUrl: 'https://apexvision.dev',
    repoUrl: 'https://github.com/teamapex/apexvision',
    techStack: ['Python', 'TensorFlow', 'Next.js', 'WebSockets'],
    submittedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'sub-4',
    teamId: 'team-4',
    teamName: 'Team Quantum',
    title: 'QuantumGrid Energy',
    tagline: 'ZK Solar Microgrid Protocol',
    description: 'Zero-knowledge energy credit trade settlement on Solana.',
    demoUrl: 'https://quantumgrid.io',
    repoUrl: 'https://github.com/teamquantum/grid',
    techStack: ['Rust', 'Solidity', 'C++', 'React'],
    submittedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'sub-5',
    teamId: 'team-5',
    teamName: 'Team CyberPulse',
    title: 'CyberPulse Sentinel',
    tagline: 'Automated Container Security Audit',
    description: 'Real-time AI vulnerability detection in Kubernetes clusters.',
    demoUrl: 'https://cyberpulse.tech',
    repoUrl: 'https://github.com/cyberpulse/sentinel',
    techStack: ['Go', 'Docker', 'Python', 'Tailwind'],
    submittedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];

export const SEEDED_EVALUATIONS: Evaluation[] = [
  // Team Nova: Evaluated by 3 judges.
  // Judge 1 (Dr. Rajesh): 36/40
  // Judge 2 (Prof. Sarah): 35/40
  // Judge 3 (Alex Chen): 15/40 -> DEVIATION FLAG! (20.5 pts below peer average of 35.5)
  {
    id: 'eval-1',
    judgeId: 'judge-1',
    judgeName: 'Dr. Rajesh Kumar',
    teamId: 'team-1',
    teamName: 'Team Nova',
    innovation: 9,
    technicalImplementation: 9,
    impact: 9,
    presentation: 9,
    totalScore: 36,
    feedback: 'Outstanding architecture, real multimodal Gemini integration with clear healthcare impact.',
    startedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    submittedAt: new Date(Date.now() - 1000 * 60 * 46).toISOString(),
    durationSeconds: 240,
    isRushed: false,
  },
  {
    id: 'eval-2',
    judgeId: 'judge-2',
    judgeName: 'Prof. Sarah Jenkins',
    teamId: 'team-1',
    teamName: 'Team Nova',
    innovation: 9,
    technicalImplementation: 9,
    impact: 9,
    presentation: 8,
    totalScore: 35,
    feedback: 'Very solid demo. Great UI and real-time patient triage queue implementation.',
    startedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    submittedAt: new Date(Date.now() - 1000 * 60 * 36).toISOString(),
    durationSeconds: 240,
    isRushed: false,
  },
  {
    id: 'eval-3',
    judgeId: 'judge-3',
    judgeName: 'Tech Lead Alex Chen',
    teamId: 'team-1',
    teamName: 'Team Nova',
    innovation: 4,
    technicalImplementation: 4,
    impact: 4,
    presentation: 3,
    totalScore: 15,
    feedback: 'Unclear backend setup. Score lower due to missing edge case documentation.',
    startedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    submittedAt: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
    durationSeconds: 180,
    isRushed: false,
    deviationFlag: {
      isFlagged: true,
      pointsBelowMean: 20.5,
      peerAverage: 35.5,
      judgeScore: 15,
    },
  },
  // Team Apex: Evaluated by Judge 1 (37/40) in 38 seconds -> RUSHED REVIEW FLAG!
  {
    id: 'eval-4',
    judgeId: 'judge-1',
    judgeName: 'Dr. Rajesh Kumar',
    teamId: 'team-3',
    teamName: 'Team Apex',
    innovation: 10,
    technicalImplementation: 9,
    impact: 9,
    presentation: 9,
    totalScore: 37,
    feedback: 'Excellent drone thermal vision navigation project.',
    startedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    submittedAt: new Date(Date.now() - 1000 * 60 * 20 + 38000).toISOString(),
    durationSeconds: 38,
    isRushed: true,
  },
  // Team Quantum: Evaluated by Judge 2 (32/40)
  {
    id: 'eval-5',
    judgeId: 'judge-2',
    judgeName: 'Prof. Sarah Jenkins',
    teamId: 'team-4',
    teamName: 'Team Quantum',
    innovation: 8,
    technicalImplementation: 8,
    impact: 8,
    presentation: 8,
    totalScore: 32,
    feedback: 'Innovative ZK microgrid protocol. Needs clearer solar metering integration.',
    startedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    submittedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    durationSeconds: 300,
    isRushed: false,
  },
];

export const SEEDED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '🚨 Schedule Update: Judging Commences in 30 Minutes',
    message: 'All teams must ensure their project repositories and demo URLs are updated in VEYRA. Judges will begin visiting tables at 16:30.',
    priority: 'URGENT',
    audience: 'EVERYONE',
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    createdBy: 'Organizer Command Center',
  },
  {
    id: 'ann-2',
    title: '⚡ Mentorship Desk Active in Innovation Lab B',
    message: 'AI/ML & Cloud Architecture mentors from Google Cloud & Firebase are available for 1-on-1 code reviews in Lab B.',
    priority: 'NORMAL',
    audience: 'PARTICIPANTS',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdBy: 'Organizer Command Center',
  },
  {
    id: 'ann-3',
    title: '⚠️ Action Required: Submit Team Project Draft',
    message: 'Teams without a submitted project link cannot be assigned to judges. Please open your Participant Dashboard and click Submit Project.',
    priority: 'CRITICAL',
    audience: 'NO_SUBMISSION_TEAMS',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdBy: 'Organizer Command Center',
  },
];

export const SEEDED_OPS_REPORTS: OpsReport[] = [
  {
    id: 'ops-1',
    reporterId: 'part-1',
    reporterName: 'Yash Gawde',
    rawText: 'Wi-Fi has completely dropped in Hall B, teams cannot push code or reach NPM',
    category: 'Wi-Fi',
    severity: 'Critical',
    summary: 'Total connectivity failure in Main Hacking Hall B affecting code deployments.',
    recommendedAction: 'Reset Access Point AP-04 in Hall B and verify DHCP lease pool.',
    status: 'IN_PROGRESS',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    location: 'Main Hacking Hall B',
  },
  {
    id: 'ops-2',
    reporterId: 'part-4',
    reporterName: 'Rohan Mehta',
    rawText: 'Extension cord sparking and power socket dead at Table 14 in Room 204',
    category: 'Power',
    severity: 'High',
    summary: 'Electrical fault and damaged power strip near Table 14.',
    recommendedAction: 'Dispatch electrical team immediately to replace Table 14 power strip.',
    status: 'ACKNOWLEDGED',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    location: 'Room 204, Table 14',
  },
  {
    id: 'ops-3',
    reporterId: 'part-7',
    reporterName: 'Neha Gupta',
    rawText: 'Drinking water dispenser on 2nd floor is empty',
    category: 'Facility',
    severity: 'Medium',
    summary: 'Refill required for 2nd floor water station.',
    recommendedAction: 'Notify catering logistics crew to refill 2nd floor water canisters.',
    status: 'RESOLVED',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    location: '2nd Floor Corridor',
  },
];

export async function seedDemoDataToFirestore() {
  try {
    // 1. Seed Participants
    for (const part of SEEDED_PARTICIPANTS) {
      await setDoc(doc(db, 'participants', part.id), part);
    }
    // 2. Seed Teams
    for (const team of SEEDED_TEAMS) {
      await setDoc(doc(db, 'teams', team.id), team);
    }
    // 3. Seed Submissions
    for (const sub of SEEDED_SUBMISSIONS) {
      await setDoc(doc(db, 'submissions', sub.id), sub);
    }
    // 4. Seed Evaluations
    for (const ev of SEEDED_EVALUATIONS) {
      await setDoc(doc(db, 'evaluations', ev.id), ev);
    }
    // 5. Seed Announcements
    for (const ann of SEEDED_ANNOUNCEMENTS) {
      await setDoc(doc(db, 'announcements', ann.id), ann);
    }
    // 6. Seed Ops Reports
    for (const ops of SEEDED_OPS_REPORTS) {
      await setDoc(doc(db, 'ops_reports', ops.id), ops);
    }
    return { success: true, count: SEEDED_PARTICIPANTS.length };
  } catch (err) {
    console.error('Firestore demo seeding error:', err);
    throw err;
  }
}
